clc
clear;
addpath(genpath('.'));
dataName = 'data/mirflickr.mat';
[result,GTLA] = PML_ND(dataName);
result
GTLA

% dataName = {'data/mirflickr.mat','data/music_emotion.mat','data/music_style.mat','data/YeastBP.mat','data/YeastCC.mat','data/YeastMF.mat',...
%     'data/PML_recreation_7.mat','data/PML_recreation_9.mat','data/PML_art_7.mat','data/PML_art_9.mat','data/PML_education_7.mat',...
%     'data/PML_education_9.mat','data/PML_science_7.mat','data/PML_science_9.mat','data/PML_health_7.mat','data/PML_health_9.mat',...
%     'data/PML_Scene_3.mat','data/PML_Scene_4.mat','data/PML_Scene_5.mat','data/PML_flags_4.mat','data/PML_flags_5.mat','data/PML_genbase_3.mat',...
%     'data/PML_genbase_4.mat','data/PML_genbase_5.mat','data/PML_slashdot_3.mat','data/PML_slashdot_4.mat','data/PML_slashdot_5.mat',...
%     'data/PML_enron_5.mat','data/PML_enron_7.mat','data/PML_enron_9.mat'};